### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by billhhh** [artvandelay/Deep_Inside_Convolutional_Networks#6]
Traceback (most recent call last):
  File "class_saliency_extraction.py", line 25, in <module>
    image_dims=(224, 224))
  File "D:/Projects/caffe-windows/caffe/python\caffe\classifier.py", line 29, in __init__
    in_ = self.inputs[0]
IndexError: list index out of range

**Comment by billhhh** [comment]
why would this happend, thank you

**Comment by billhhh** [comment]
after I change my input as yours in prototxt, it became

F0915 10:38:30.031225   880 insert_splits.cpp:29] Unknown bottom blob 'label' (layer 'loss1/loss', bottom index 1)
*** Check failure stack trace: ***

**Comment by billhhh** [comment]
all solved, thanks
